name: PyPI Publishing

on:
  push:
    branches:    
      - master

jobs:
  publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
      - name: Publish package distributions to PyPI
        run: pdm publish
